services:
  config-service:
    build: ./config-service
    container_name: config-service
    ports:
      - "8888:8888"
    networks:
      - tcnet

  eureka-service:
    build: ./eureka-service
    container_name: eureka-service
    ports:
      - "8761:8761"
    environment:
      CONFIG_SERVER: ${CONFIG_SERVER}      
    depends_on:
      - config-service
    networks:
      - tcnet

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      CONFIG_SERVER: ${CONFIG_SERVER}
      AUTHORIZATION_JWT_SECRET: ${AUTHORIZATION_JWT_SECRET}
      AUTHORIZATION_JWT_EXP: ${AUTHORIZATION_JWT_EXP}
      EUREKA_URL: ${EUREKA_URL}
    networks:
      - tcnet

  identity-service:
    build: ./identity-service
    container_name: identity-service
    ports:
      - "8100:8100"
    environment:
      CONFIG_SERVER: ${CONFIG_SERVER}
      DB_URL_IDENTITY_SERVICE: ${DB_URL_IDENTITY_SERVICE}
      DB_USERNAME_IDENTITY_SERVICE: ${DB_USERNAME_IDENTITY_SERVICE}
      DB_PASSWORD_IDENTITY_SERVICE: ${DB_PASSWORD_IDENTITY_SERVICE}
      PSWD: ${PSWD}
      AUTHORIZATION_JWT_SECRET: ${AUTHORIZATION_JWT_SECRET}
      AUTHORIZATION_JWT_EXP: ${AUTHORIZATION_JWT_EXP}
      EUREKA_URL: ${EUREKA_URL}
      COMPANY_SERVICE_URL: ${COMPANY_SERVICE_URL}
    depends_on:
      - config-service
      - eureka-service
    networks:
      - tcnet

  labor-record-service:
    build: ./labor-record-service
    container_name: labor-record-service
    ports:
      - "8105:8105"
    environment:
      CONFIG_SERVER: ${CONFIG_SERVER}
      DB_URL_LABOR_RECORD_SERVICE: ${DB_URL_LABOR_RECORD_SERVICE}
      DB_USERNAME_LABOR_RECORD_SERVICE: ${DB_USERNAME_LABOR_RECORD_SERVICE}
      DB_PASSWORD_LABOR_RECORD_SERVICE: ${DB_PASSWORD_LABOR_RECORD_SERVICE}
      IDENTITY_SERVICE_URL: ${IDENTITY_SERVICE_URL}
      TRX_SERVICE_URL: ${TRX_SERVICE_URL}
      EUREKA_URL: ${EUREKA_URL}
    depends_on:
      - config-service
      - eureka-service
      - gateway-service
    networks:
      - tcnet

  company-service:
    build: ./company-service
    container_name: company-service
    ports:
      - "8090:8090"
    environment:
      CONFIG_SERVER: ${CONFIG_SERVER}
      DB_URL_COMPANY_SERVICE: ${DB_URL_COMPANY_SERVICE}
      DB_USERNAME_COMPANY_SERVICE: ${DB_USERNAME_COMPANY_SERVICE}
      DB_PASSWORD_COMPANY_SERVICE: ${DB_PASSWORD_COMPANY_SERVICE}
      EUREKA_URL: ${EUREKA_URL}
    depends_on:
      - config-service
      - eureka-service
      - gateway-service
    networks:
      - tcnet
  
  transactions-service:
    build: ./transactions-service
    container_name: transactions-service
    ports:
      - "8120:8120"
    environment:
      CONFIG_SERVER: ${CONFIG_SERVER}
      DB_URL_TRX_SERVICE: ${DB_URL_TRX_SERVICE}
      DB_USERNAME_TRX_SERVICE: ${DB_USERNAME_TRX_SERVICE}
      DB_PASSWORD_TRX_SERVICE: ${DB_PASSWORD_TRX_SERVICE}
      COMPANY_SERVICE_URL: ${COMPANY_SERVICE_URL}
      EUREKA_URL: ${EUREKA_URL}
      RPC_URL: ${RPC_URL}
      PRIVATE_KEY: ${PRIVATE_KEY}
    depends_on:
      - config-service
      - eureka-service
      - gateway-service
    networks:
      - tcnet

networks:
  tcnet:
    driver: bridge