server:
  port: 8090

spring:
  datasource:
    url: ${DB_URL_COMPANY_SERVICE}
    username: ${DB_USERNAME_COMPANY_SERVICE}
    password: ${DB_PASSWORD_COMPANY_SERVICE}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    hostname: company-service
    #hostname: localhost
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
      #default-zone: ${EUREKA_URL:http://localhost:8761/eureka}