server:
  port: 8095

spring:
  application:
    name: gamification-service



eureka:
  instance:
    hostname: localhost
    #hostname: gamification-service
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
      #defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}