server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
      #defaultZone: ${EUREKA_URL}
  instance:
    #hostname: gateway-service
    hostname: localhost

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins: "*"
                allowedHeaders: "*"
                allowedMethods:
                  - GET
                  - POST
                  - DELETE
                  - PUT
                  - OPTIONS
                  - PATCH
          routes:
            - id: identity
              uri: lb://identity-service
              predicates:
                - Path=/api/v1/auth/**
            - id: users
              uri: lb://identity-service
              predicates:
                - Path=/api/v1/users/**
              filters:
                - AuthenticationFilter
            - id: employees
              uri: lb://identity-service
              predicates:
                - Path=/api/v1/employees/**
              filters:
                - AuthenticationFilter
            - id: evidences
              uri: lb://labor-record-service
              predicates:
                - Path=/api/v1/evidences/**
              filters:
                - AuthenticationFilter

authorization:
  jwt:
    secret: ${AUTHORIZATION_JWT_SECRET}
    expiration:
      days: ${AUTHORIZATION_JWT_EXP}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      access:
        enabled: true