server:
  port: 8100

spring:
  application:
    name: identity-service

authorization:
  jwt:
    secret: WriteHereYourSecretStringForTokenSigningCredentials
    expiration:
      days: 14

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka