server:
  port: 8105

spring:
  application:
    name: labor-record-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL_LABOR_RECORD_SERVICE}
    username: ${DB_USERNAME_LABOR_RECORD_SERVICE}
    password: ${DB_PASSWORD_LABOR_RECORD_SERVICE}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

clients:
  identity:
    base-url: ${IDENTITY_SERVICE_URL}

eureka:
  instance:
    hostname: labor-record-service
    #hostname: localhost
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
      #defaultZone: http://localhost:8761/eureka